/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import entity.Address;
import entity.Centre;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import util.Checker;
import util.Convert;
import util.Editable;
import util.InitDictionary;
import util.Transfer;

/**
 *
 * @author LEGION
 */
public class AdminCentre extends javax.swing.JFrame implements Editable {

    private boolean idFilled;
    private boolean cleared;
    private int pointer;
    private DefaultTableModel tblModel;
    private DefaultListModel lstSearchModel;
    private List<Integer> searchIdx;
    private Map<String, Centre> centreDict;


    /**
     * Creates new form AdminCentre
     */
    public AdminCentre() {
        initComponents();
        this.setLocationRelativeTo(null);
        centreDict = InitDictionary.centreData();
        searchIdx = new ArrayList<>();
        pointer = 0;
        cleared = true;
        idFilled = false;
        tblModel = (DefaultTableModel) tblCentre.getModel();
        lstSearch.setModel(new DefaultListModel());
        lstSearchModel = (DefaultListModel) lstSearch.getModel();
        btnOk.setVisible(false);
        btnCancel.setVisible(false);
        btnClear.setVisible(false);
        btnCancel.doClick();
    }

    public String check() {
        if (!Checker.isCentreID(txtCID.getText()) || txtCName.getText().isBlank() ||
                txtCStreet.getText().isBlank() || txtCCity.getText().isBlank()) {
            return "Please do not leave text field in blank";
        }
        char[] bad = {
            ';',
            '_',
        };
        if (!Checker.hasNoBadChar(txtCName.getText(), bad))
            return "Bad character in centre name";
        if (!Checker.hasNoBadChar(txtCStreet.getText(), bad))
            return "Bad character in centre street";
        if (!Checker.hasNoBadChar(txtCCity.getText(), bad))
            return "Bad character in centre city";
        return null;
    }

    @Override
    public void enableDisableButton(boolean state) {
        tglAdd.setEnabled(state);
        tglModify.setEnabled(state);
        btnView.setEnabled(state);
        btnSearch.setEnabled(state);
        lstSearch.setEnabled(state);
        tblCentre.setEnabled(state);
    }

    @Override
    public void enableDisablePanel(boolean state) {
        txtCID.setEnabled(state);
        txtCName.setEnabled(state);
        txtCStreet.setEnabled(state);
        txtCCity.setEnabled(state);
    }

    @Override
    public void write() {
        if (tglAdd.isSelected()) {
            for (String id: centreDict.keySet()) {
                if (id.equals(txtCID.getText())) {
                    PopupDialog.error("Duplicate centre ID");
                    return;
                }
            }
            Address addr = new Address(txtCStreet.getText(),
                    txtCCity.getText());
            Centre newC = new Centre(txtCID.getText(),
                    txtCName.getText(), addr);
            newC.initStock();
            centreDict.put(txtCID.getText(), newC);
        }
        else {
            Centre selected = centreDict.get(txtCID.getText());
            selected.setName(txtCName.getText());
            Address addr = new Address(txtCStreet.getText(),
                    txtCCity.getText());
            selected.setAddr(addr);
        }
        Centre[] cenArr = centreDict.values().toArray(new Centre[0]);
        Transfer.exportObject(cenArr, Centre.FILENAME);
    }

    @Override
    public void fillDetails() {
        // pointer == -1 when the table is disabled but clicked
        if (pointer != -1) {
            txtCID.setText((String) tblCentre.getValueAt(pointer, 0));
            txtCName.setText((String) tblCentre.getValueAt(pointer, 1));
            txtCStreet.setText((String) tblCentre.getValueAt(pointer, 2));
            txtCCity.setText((String) tblCentre.getValueAt(pointer, 3));
            cleared = false;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogSearch = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        dialogTxtSearch = new javax.swing.JTextField();
        dialogCbxCategory = new javax.swing.JComboBox<>();
        dialogBtnCancel = new javax.swing.JButton();
        dialogBtnOk = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnPeople = new javax.swing.JButton();
        btnAppointment = new javax.swing.JButton();
        btnSupply = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        btnVaccine = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        tglAdd = new javax.swing.JToggleButton();
        tglModify = new javax.swing.JToggleButton();
        btnSearch = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCID = new javax.swing.JTextField();
        txtCName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCStreet = new javax.swing.JTextField();
        txtCCity = new javax.swing.JTextField();
        btnOk = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstSearch = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCentre = new javax.swing.JTable();

        dialogSearch.setTitle("Search");
        dialogSearch.setResizable(false);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Search");

        dialogCbxCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Centre ID", "Centre Name", "Street", "City" }));

        dialogBtnCancel.setText("Cancel");
        dialogBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogBtnCancelActionPerformed(evt);
            }
        });

        dialogBtnOk.setText("OK");
        dialogBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogBtnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(dialogTxtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(dialogCbxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dialogBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dialogBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(dialogTxtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialogCbxCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dialogBtnCancel)
                    .addComponent(dialogBtnOk))
                .addContainerGap())
        );

        javax.swing.GroupLayout dialogSearchLayout = new javax.swing.GroupLayout(dialogSearch.getContentPane());
        dialogSearch.getContentPane().setLayout(dialogSearchLayout);
        dialogSearchLayout.setHorizontalGroup(
            dialogSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogSearchLayout.setVerticalGroup(
            dialogSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Centre (Admin)");

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        btnPeople.setText("People");
        btnPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPeopleActionPerformed(evt);
            }
        });

        btnAppointment.setText("Appointment");
        btnAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointmentActionPerformed(evt);
            }
        });

        btnSupply.setText("Supply");
        btnSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplyActionPerformed(evt);
            }
        });

        jButton10.setText("Centre");
        jButton10.setEnabled(false);

        btnVaccine.setText("Vaccine");
        btnVaccine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaccineActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAppointment, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSupply, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPeople)
                    .addComponent(btnAppointment)
                    .addComponent(btnSupply)
                    .addComponent(jButton10)
                    .addComponent(btnVaccine)
                    .addComponent(btnLogout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tglAdd.setText("Add");
        tglAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglAddActionPerformed(evt);
            }
        });

        tglModify.setText("Modify");
        tglModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglModifyActionPerformed(evt);
            }
        });

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Centre ID");

        jLabel2.setText("Centre Name");

        txtCID.setForeground(new java.awt.Color(204, 204, 204));
        txtCID.setText("CXXX");
        txtCID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCIDFocusLost(evt);
            }
        });

        jLabel3.setText("Address");

        jLabel4.setText("Street");

        jLabel5.setText("City");

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCName)
                            .addComponent(txtCID, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                            .addComponent(txtCStreet)
                            .addComponent(txtCCity)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtCStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtCCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancel)
                    .addComponent(btnClear))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel3);

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        lstSearch.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstSearch.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstSearchValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstSearch);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tglAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tglModify, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglAdd)
                    .addComponent(tglModify)
                    .addComponent(btnView))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
        );

        tblCentre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblCentre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCentreMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCentre);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        String result = check();
        if (result != null) {
            PopupDialog.error(result);
            return;
        }
        write();
        btnCancel.doClick();
        btnView.doClick();
    }//GEN-LAST:event_btnOkActionPerformed

    private void txtCIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCIDFocusGained
        // TODO add your handling code here:
        txtCID.setForeground(Color.black);
        if (txtCID.getText().equals("CXXX") && !idFilled)
            txtCID.setText("");
    }//GEN-LAST:event_txtCIDFocusGained

    private void txtCIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCIDFocusLost
        // TODO add your handling code here:
        if (txtCID.getText().isBlank()) {
            txtCID.setForeground(Color.lightGray);
            txtCID.setText("CXXX");
            idFilled = false;
        }
        else {
            boolean valid = Checker.isCentreID(txtCID.getText());
            if (!valid) {
                txtCID.setForeground(Color.red);
            }
            idFilled = true;
        }
    }//GEN-LAST:event_txtCIDFocusLost

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        tblModel.setRowCount(0);
        pointer = 0;
        Centre[] cenArr = centreDict.values().toArray(new Centre[0]);
        Object[] colId = {
            "Centre ID",
            "Centre Name",
            "Street",
            "City"
        };
        tblModel.setColumnIdentifiers(colId);
        for (Centre ctr: cenArr) {
            String[] temp = {
                ctr.getCentreID(),
                ctr.getName(),
                ctr.getAddr().getStreet(),
                ctr.getAddr().getCity(),
            };
            tblModel.addRow(temp);
        }

    }//GEN-LAST:event_btnViewActionPerformed

    private void tglAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglAddActionPerformed
        // TODO add your handling code here:
        if (tglAdd.isSelected()) {
            enableDisableButton(false);
            enableDisablePanel(true);
            tglAdd.setEnabled(true);
            btnOk.setVisible(true);
            btnCancel.setVisible(true);
            btnClear.setVisible(true);
        }
        else {
            btnCancel.doClick();
            enableDisableButton(true);
            enableDisablePanel(false);
            btnOk.setVisible(false);
            btnCancel.setVisible(false);
            btnClear.setVisible(false);
        }
    }//GEN-LAST:event_tglAddActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        btnClear.doClick();
        enableDisableButton(true);
        enableDisablePanel(false);
        btnOk.setVisible(false);
        btnCancel.setVisible(false);
        btnClear.setVisible(false);
        tglAdd.setSelected(false);
        tglModify.setSelected(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        txtCID.setText("CXXX");
        txtCID.setForeground(Color.lightGray);
        txtCName.setText("");
        txtCCity.setText("");
        txtCStreet.setText("");
        cleared = true;
    }//GEN-LAST:event_btnClearActionPerformed

    private void tglModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglModifyActionPerformed
        // TODO add your handling code here:
        if (tglModify.isSelected() && !cleared) {
            enableDisableButton(false);
            enableDisablePanel(true);
            txtCID.setEnabled(false);
            tglModify.setEnabled(true);
            btnOk.setVisible(true);
            btnCancel.setVisible(true);
            btnClear.setVisible(true);
        }
        else {
            PopupDialog.error("Please select an entry first");
            btnCancel.doClick();
            btnOk.setVisible(false);
            btnCancel.setVisible(false);
            btnClear.setVisible(false);
        }
    }//GEN-LAST:event_tglModifyActionPerformed

    private void tblCentreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCentreMouseClicked
        // TODO add your handling code here:
        pointer = tblCentre.getSelectedRow();
        fillDetails();
    }//GEN-LAST:event_tblCentreMouseClicked

    private void btnPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPeopleActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminPeople().setVisible(true);
    }//GEN-LAST:event_btnPeopleActionPerformed

    private void btnAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointmentActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminAppoint().setVisible(true);
    }//GEN-LAST:event_btnAppointmentActionPerformed

    private void btnSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplyActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminSupply().setVisible(true);
    }//GEN-LAST:event_btnSupplyActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        dialogSearch.setLocationRelativeTo(this);
        dialogSearch.pack();
        dialogSearch.setVisible(true);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnVaccineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaccineActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new AdminVaccine().setVisible(true);
    }//GEN-LAST:event_btnVaccineActionPerformed

    private void dialogBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogBtnOkActionPerformed
        // TODO add your handling code here:
        btnView.doClick();
        searchIdx.clear();
        lstSearchModel.removeAllElements();
        int row = tblCentre.getRowCount();
        int col = tblCentre.getColumnCount();
        int selectedCol = dialogCbxCategory.getSelectedIndex();
        String keyword = dialogTxtSearch.getText();
        if (keyword.isBlank()) {
            return;
        }

        keyword = Convert.escapeSpecialChar(keyword);
        keyword = ".*" + keyword + ".*";

        Pattern pattern = Pattern.compile(keyword, Pattern.CASE_INSENSITIVE);
        Matcher matcher;

        for (int i = 0; i < row; i++) {
            String cell = tblCentre.getValueAt(i, selectedCol).toString();
            matcher = pattern.matcher(cell);
            if (matcher.find()) {
                searchIdx.add(i);
                String[] temp = new String[col];
                for (int j = 0; j < col; j++) {
                    temp[j] = tblCentre.getValueAt(i, j).toString();
                }
                lstSearchModel.addElement(String.join(";", temp));
            }
        }
    }//GEN-LAST:event_dialogBtnOkActionPerformed

    private void lstSearchValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstSearchValueChanged
        // TODO add your handling code here:
        try {
            int idx = lstSearch.getSelectedIndex();
            pointer = searchIdx.get(idx);
            fillDetails();
        }
        catch (IndexOutOfBoundsException e) {
        }
    }//GEN-LAST:event_lstSearchValueChanged

    private void dialogBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogBtnCancelActionPerformed
        // TODO add your handling code here:
        dialogSearch.dispose();
    }//GEN-LAST:event_dialogBtnCancelActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        btnPeopleetails see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminCentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminCentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminCentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCentre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminCentre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointment;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnPeople;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSupply;
    private javax.swing.JButton btnVaccine;
    private javax.swing.JButton btnView;
    private javax.swing.JButton dialogBtnCancel;
    private javax.swing.JButton dialogBtnOk;
    private javax.swing.JComboBox<String> dialogCbxCategory;
    private javax.swing.JDialog dialogSearch;
    private javax.swing.JTextField dialogTxtSearch;
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstSearch;
    private javax.swing.JTable tblCentre;
    private javax.swing.JToggleButton tglAdd;
    private javax.swing.JToggleButton tglModify;
    private javax.swing.JTextField txtCCity;
    private javax.swing.JTextField txtCID;
    private javax.swing.JTextField txtCName;
    private javax.swing.JTextField txtCStreet;
    // End of variables declaration//GEN-END:variables
}
