/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.toedter.calendar.JTextFieldDateEditor;
import entity.*;
import java.time.LocalDate;
import java.time.Month;
import java.util.Map;
import util.Checker;
import util.Convert;
import util.InitDictionary;
import util.Transfer;

/**
 *
 * @author LEGION
 */
public class UserAccount extends javax.swing.JFrame {

    private People user;
    private JTextFieldDateEditor dcEditor;
    private Map<String, Citizen> czDict;
    private Map<String, NonCitizen> nczDict;
    
    /**
     * Creates new form UserInfo
     */
    public UserAccount() {
        this.nczDict = InitDictionary.noncitizenDict();
        this.czDict = InitDictionary.citizenDict();
        initComponents();
        this.setLocationRelativeTo(null);
        this.user = czDict.get("IC000001");
        txtICP.setEditable(false);
        txtICP.setText(this.user.getID());
        txtName.setText(this.user.getName());
        txtEmail.setText(this.user.getEmail());
        txtPhone.setText(this.user.getPhoneNumber());
        LocalDate now = LocalDate.now();
        LocalDate min = LocalDate.of(1800, Month.JANUARY, 1);
        dcDOB.setMaxSelectableDate(Convert.LocalDateToDate(now));
        dcDOB.setMinSelectableDate(Convert.LocalDateToDate(min));
        dcEditor = (JTextFieldDateEditor) dcDOB.getDateEditor();
        dcEditor.setEditable(false);
        dcEditor.setDate(Convert.LocalDateToDate(this.user.getDOB()));
        editMode(false);
    }

    public UserAccount(People user) {
        this.nczDict = InitDictionary.noncitizenDict();
        this.czDict = InitDictionary.citizenDict();
        initComponents();
        this.setLocationRelativeTo(null);
        if (user instanceof Citizen) {
            this.user = czDict.get(user.getID());
            lblICPNum.setText("IC Number");
        }
        else {
            this.user = nczDict.get(user.getID());
            lblICPNum.setText("Passport Number");
        }
        txtICP.setEditable(false);
        txtICP.setText(this.user.getID());
        txtName.setText(this.user.getName());
        txtEmail.setText(this.user.getEmail());
        txtPhone.setText(this.user.getPhoneNumber());
        LocalDate now = LocalDate.now();
        LocalDate min = LocalDate.of(1800, Month.JANUARY, 1);
        dcDOB.setMaxSelectableDate(Convert.LocalDateToDate(now));
        dcDOB.setMinSelectableDate(Convert.LocalDateToDate(min));
        dcEditor = (JTextFieldDateEditor) dcDOB.getDateEditor();
        dcEditor.setEditable(false);
        dcEditor.setDate(Convert.LocalDateToDate(this.user.getDOB()));
        editMode(false);
    }

    public void editMode(boolean state) {
        dcDOB.setEnabled(state);
        txtEmail.setEditable(state);
        txtPhone.setEditable(state);
        txtName.setEditable(state);
        btnOk.setVisible(state);
        btnCancel.setVisible(state);
    }

    public String check() {
        if (
                txtName.getText().isBlank() || 
                txtEmail.getText().isBlank() ||
                txtPhone.getText().isBlank() ||
                dcDOB.getDate() == null
            ) {
            return "Please do not leave fields in blank";
        }

        if (!Checker.isEmail(txtEmail.getText()) && !txtEmail.getText().equals("-")) {
            return "Invalid email address";
        }

        if (!Checker.isPhone(txtPhone.getText()) && !txtPhone.getText().equals("-")) {
            return "Invalid phone number";
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogChgPasswd = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        passFieldCur = new javax.swing.JPasswordField();
        passFieldNew = new javax.swing.JPasswordField();
        passFieldRetype = new javax.swing.JPasswordField();
        cbxCur = new javax.swing.JCheckBox();
        cbxNew = new javax.swing.JCheckBox();
        cbxRetype = new javax.swing.JCheckBox();
        dialogBtnCancel = new javax.swing.JButton();
        dialogBtnOk = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnAppoint = new javax.swing.JButton();
        btnCentre = new javax.swing.JButton();
        btnVac = new javax.swing.JButton();
        btnVacStatus = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblICPNum = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tglEdit = new javax.swing.JToggleButton();
        btnChgPasswd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnOk = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtICP = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        dcDOB = new com.toedter.calendar.JDateChooser();

        dialogChgPasswd.setTitle("Change Password");
        dialogChgPasswd.setModal(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Current password");

        jLabel6.setText("New password");

        jLabel7.setText("Re-type new password");

        cbxCur.setBackground(new java.awt.Color(255, 255, 255));
        cbxCur.setText("Show password");
        cbxCur.setFocusable(false);
        cbxCur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCurActionPerformed(evt);
            }
        });

        cbxNew.setBackground(new java.awt.Color(255, 255, 255));
        cbxNew.setText("Show password");
        cbxNew.setFocusable(false);
        cbxNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNewActionPerformed(evt);
            }
        });

        cbxRetype.setBackground(new java.awt.Color(255, 255, 255));
        cbxRetype.setText("Show password");
        cbxRetype.setFocusable(false);
        cbxRetype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRetypeActionPerformed(evt);
            }
        });

        dialogBtnCancel.setText("Cancel");
        dialogBtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogBtnCancelActionPerformed(evt);
            }
        });

        dialogBtnOk.setText("OK");
        dialogBtnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogBtnOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(passFieldNew)
                    .addComponent(passFieldRetype, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                    .addComponent(passFieldCur))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxCur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxRetype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dialogBtnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dialogBtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(passFieldCur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxCur))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passFieldNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxNew))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(passFieldRetype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxRetype))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dialogBtnCancel)
                    .addComponent(dialogBtnOk))
                .addContainerGap())
        );

        javax.swing.GroupLayout dialogChgPasswdLayout = new javax.swing.GroupLayout(dialogChgPasswd.getContentPane());
        dialogChgPasswd.getContentPane().setLayout(dialogChgPasswdLayout);
        dialogChgPasswdLayout.setHorizontalGroup(
            dialogChgPasswdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        dialogChgPasswdLayout.setVerticalGroup(
            dialogChgPasswdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Account");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("My Account");
        jButton1.setEnabled(false);

        btnAppoint.setText("Appointment");
        btnAppoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAppointActionPerformed(evt);
            }
        });

        btnCentre.setText("Centre");
        btnCentre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCentreActionPerformed(evt);
            }
        });

        btnVac.setText("Vaccine");
        btnVac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVacActionPerformed(evt);
            }
        });

        btnVacStatus.setText("Vaccination Status");
        btnVacStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVacStatusActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(btnAppoint)
                .addGap(18, 18, 18)
                .addComponent(btnCentre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVac, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVacStatus)
                .addGap(18, 18, 18)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnAppoint)
                    .addComponent(btnCentre)
                    .addComponent(btnVac)
                    .addComponent(btnVacStatus)
                    .addComponent(btnLogout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblICPNum.setText("IC/P Number");

        jLabel1.setText("Date of Birth");

        jLabel2.setText("Email Address");

        jLabel3.setText("Phone Number");

        tglEdit.setText("Edit");
        tglEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglEditActionPerformed(evt);
            }
        });

        btnChgPasswd.setText("Change Password");
        btnChgPasswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChgPasswdActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel4.setText("Name");

        dcDOB.setDateFormatString("dd/MM/yyyy");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnChgPasswd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tglEdit)
                            .addComponent(lblICPNum, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtName, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dcDOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 510, Short.MAX_VALUE)
                            .addComponent(txtICP, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtICP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblICPNum))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(32, 61, Short.MAX_VALUE)
                .addComponent(tglEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChgPasswd)
                    .addComponent(btnCancel)
                    .addComponent(btnOk))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglEditActionPerformed
        // TODO add your handling code here:
        editMode(tglEdit.isSelected());
    }//GEN-LAST:event_tglEditActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // TODO add your handling code here:
        String result = check();
        if (result == null) {
            user.setName(txtName.getText());
            user.setEmail(txtEmail.getText());
            user.setPhoneNumber(txtPhone.getText());
            user.setDOB(Convert.DateToLocalDate(dcDOB.getDate()));
            if (user instanceof Citizen) {
                Citizen[] czArr = czDict.values().toArray(new Citizen[0]);
                Transfer.exportObject(czArr, Citizen.FILENAME);
            }
            else {
                NonCitizen[] nczArr = nczDict.values().toArray(new NonCitizen[0]);
                Transfer.exportObject(nczArr, NonCitizen.FILENAME);
            }
            PopupDialog.notif("Edit successful");
            tglEdit.doClick();
        }
        else {
            PopupDialog.error(result);
        }
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        tglEdit.doClick();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnChgPasswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChgPasswdActionPerformed
        // TODO add your handling code here:
        dialogChgPasswd.setLocationRelativeTo(this);
        dialogChgPasswd.pack();
        dialogChgPasswd.setVisible(true);
    }//GEN-LAST:event_btnChgPasswdActionPerformed

    private void dialogBtnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogBtnOkActionPerformed
        // TODO add your handling code here:
        String curPasswd = String.valueOf(passFieldCur.getPassword());
        String newPasswd = String.valueOf(passFieldNew.getPassword());
        String rePasswd = String.valueOf(passFieldRetype.getPassword());
        if (!curPasswd.equals(user.getPassword())) {
            PopupDialog.error("Current password does not match record");
            return;
        }
        if (!Checker.isPassword(newPasswd) || !Checker.isPassword(rePasswd)) {
            PopupDialog.error("Password should contain at least 8 combination of alphanumeric characters");
            return;
        }
        if (!newPasswd.equals(rePasswd)) {
            PopupDialog.error("New password and Re-type password does not match");
            return;
        }
        if (newPasswd.equals(curPasswd)) {
            PopupDialog.error("New password should be different from current password");
            return;
        }
        PopupDialog.notif("Password has been changed successfully");
        user.setPassword(newPasswd);
        if (user instanceof Citizen) {
            Citizen[] czArr = czDict.values().toArray(new Citizen[0]);
            Transfer.exportObject(czArr, Citizen.FILENAME);
        }
        else {
            NonCitizen[] nczArr = nczDict.values().toArray(new NonCitizen[0]);
            Transfer.exportObject(nczArr, NonCitizen.FILENAME);
        }
        dialogChgPasswd.dispose();
    }//GEN-LAST:event_dialogBtnOkActionPerformed

    private void cbxCurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCurActionPerformed
        // TODO add your handling code here:
        if (cbxCur.isSelected()) {
            passFieldCur.setEchoChar((char) 0);
        }
        else {
            passFieldCur.setEchoChar('*');
        }
    }//GEN-LAST:event_cbxCurActionPerformed

    private void cbxNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNewActionPerformed
        // TODO add your handling code here:
        if (cbxNew.isSelected()) {
            passFieldNew.setEchoChar((char) 0);
        }
        else {
            passFieldNew.setEchoChar('*');
        }
    }//GEN-LAST:event_cbxNewActionPerformed

    private void cbxRetypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRetypeActionPerformed
        // TODO add your handling code here:
        if (cbxRetype.isSelected()) {
            passFieldRetype.setEchoChar((char) 0);
        }
        else {
            passFieldRetype.setEchoChar('*');
        }
    }//GEN-LAST:event_cbxRetypeActionPerformed

    private void dialogBtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogBtnCancelActionPerformed
        // TODO add your handling code here:
        dialogChgPasswd.dispose();
    }//GEN-LAST:event_dialogBtnCancelActionPerformed

    private void btnAppointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAppointActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new UserAppoint(user).setVisible(true);
    }//GEN-LAST:event_btnAppointActionPerformed

    private void btnCentreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCentreActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new UserCentre(user).setVisible(true);
    }//GEN-LAST:event_btnCentreActionPerformed

    private void btnVacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVacActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new UserVaccine(user).setVisible(true);
    }//GEN-LAST:event_btnVacActionPerformed

    private void btnVacStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVacStatusActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new UserStatus(user).setVisible(true);
    }//GEN-LAST:event_btnVacStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppoint;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCentre;
    private javax.swing.JButton btnChgPasswd;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnVac;
    private javax.swing.JButton btnVacStatus;
    private javax.swing.JCheckBox cbxCur;
    private javax.swing.JCheckBox cbxNew;
    private javax.swing.JCheckBox cbxRetype;
    private com.toedter.calendar.JDateChooser dcDOB;
    private javax.swing.JButton dialogBtnCancel;
    private javax.swing.JButton dialogBtnOk;
    private javax.swing.JDialog dialogChgPasswd;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblICPNum;
    private javax.swing.JPasswordField passFieldCur;
    private javax.swing.JPasswordField passFieldNew;
    private javax.swing.JPasswordField passFieldRetype;
    private javax.swing.JToggleButton tglEdit;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtICP;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
